In [1]:
import numpy as np


def calculate(list):
    if (len(list) != 9):
        raise ValueError("List must contain nine numbers.")

    b = np.reshape( list, (3,3) )
    print(b)

 
    mean1 = np.mean(b, axis=0).tolist()  
    mean2 = np.mean(b, axis=1).tolist()

    var1=  np.var(b, axis=0).tolist()
    var2= np.var(b, axis=1).tolist()

    std1= np.std(b, axis=0).tolist()
    std2= np.std(b, axis=1).tolist()

    max1= np.max(b, axis=0).tolist()
    max2= np.max(b, axis=1).tolist()

    min1= np.min(b, axis=0).tolist()
    min2= np.min(b, axis=1).tolist()

    sum1= np.sum(b, axis=0).tolist()
    sum2= np.sum(b, axis=1).tolist()

   


    return {
     "mean": [mean1, mean2, b.mean()],
     'variance': [var1, var2, b.var()],
     'standard deviation': [std1, std2, b.std()],
     'max': [max1, max2, b.max()],
     'min': [min1, min2, b.min()],
     'sum': [sum1, sum2, b.sum()]
      }



In [2]:
list = ([ 23, 55, 13, 54, 54, 66, 87, 88, 13])

In [3]:
calculate(list)

[[23 55 13]
 [54 54 66]
 [87 88 13]]


{'mean': [[54.666666666666664, 65.66666666666667, 30.666666666666668],
  [30.333333333333332, 58.0, 62.666666666666664],
  50.333333333333336],
 'variance': [[682.8888888888888, 249.55555555555554, 624.2222222222221],
  [320.88888888888886, 32.0, 1233.5555555555554],
  732.4444444444445],
 'standard deviation': [[26.132142830026183,
   15.797327481430381,
   24.984439601924677],
  [17.9133717900592, 5.656854249492381, 35.122009560324926],
  27.063710840245918],
 'max': [[87, 88, 66], [55, 66, 88], 88],
 'min': [[23, 54, 13], [13, 54, 13], 13],
 'sum': [[164, 197, 92], [91, 174, 188], 453]}